/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author User
 */
public enum Operacija implements Serializable {
    LOGIN,
    UCITAJ_KLIJENTE, OBRISI_KLIJENTA, DODAJ_KLIJENTA, UCITAJ_MESTA,AZURIRAJ_KLIJENTA, UCITAJ_IZNAJMLJIVANJA, UCITAJ_STAVKE, OBRISI_MESTO, DODAJ_MESTO, AZURIRAJ_MESTO, UCITAJ_IGRAONICE, OBRISI_IGRAONICU, DODAJ_IGRAONICU, AZURIRAJ_IGRAONICU, UCITAJ_ZAPOSLENE, OBRISI_ZAPOSLENOG, DODAJ_ZAPOSLENOG, AZURIRAJ_ZAPOSLENOG, UCITAJ_SMENE, UCITAJ_ZAPOSLENISMENA, DODAJ_ZAPOSLENISMENA, OBRISI_ZAPOSLENOISMENA, AZURIRAJ_ZAPOSLENISMENA, DODAJ_IZNAJMLJIVANJE, OBRISI_IZNAJMLJIVANJE, AZURIRAJ_IZNAJMLJIVANJE, DODAJ_SMENU, OBRISI_SMENU,
}
